version: '3.8'
services:
  mongodb:
    image: wmsolar/mongodb-prod:latest
    restart: always
    volumes: 
      - type: volume
        source: mongodbdata
        target: /data/db
        volume:
          nocopy: true
    ports: 
      - "27017:27017"
    networks:
      - overlay

  backend-service:
    build: .
    image: wmsolar/nodejs-express:latest
    restart: always
    networks:
      - overlay
    privileged: true
    ports:
      - "3001:3001"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
       
volumes: 
  mongodbdata:
    external: true
    
networks:
   overlay: 
         
