version: '3.8'
services:
  mongodb:
    image: wmsolar/solardev:database
    container_name: mongodb
    restart: always
    volumes: 
      - type: volume
        source: mongodbdata
        target: /data/db
        volume:
          nocopy: true
    ports: 
      - "27017:27017"
    networks:
      - overlay

  backend-service:
    build: .
    image: wmsolar/express-api:latest
    container_name: backend-service
    networks:
      - overlay
    privileged: true
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
       
volumes: 
  mongodbdata:
    external: true
    
networks:
   overlay:
